config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.13-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-ingress.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-sa.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.13 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.13 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.16-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.16 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.16 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.17-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.17 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.17 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.18-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.18 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.18 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.21-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.21 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.21 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.22-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.22 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.22 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.23-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.23 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.23 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.24-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.24 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.24 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.26-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.26 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.26 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.27-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.27 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.27 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.28-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.28 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.28 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.29-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.29 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.29 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.30-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.30 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.30 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.31-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.31 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.31 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-0.0.2-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-ingress.yaml, config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-jx3-demoapp6-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-jx3-demoapp6-sa.yaml, config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp6 to version 0.0.2 in Staging environment
=> chore: promote jx3-demoapp6 to version 0.0.2 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-0.0.3-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-jx3-demoapp6-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp6 to version 0.0.3 in Staging environment
=> chore: promote jx3-demoapp6 to version 0.0.3 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-0.0.4-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-jx3-demoapp6-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp6/jx3-demoapp6-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp6 to version 0.0.4 in Staging environment
=> chore: promote jx3-demoapp6 to version 0.0.4 in Staging environment

config-root/namespaces/jx-production/jx3-demoapp5/jx3-demoapp5-0.0.31-release.yaml, config-root/namespaces/jx-production/jx3-demoapp5/jx3-demoapp5-ingress.yaml, config-root/namespaces/jx-production/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-production/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-sa.yaml, config-root/namespaces/jx-production/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.31 in Production environment
=> chore: promote jx3-demoapp5 to version 0.0.31 in Production environment

config-root/namespaces/jx-production/jx3-demoapp6/jx3-demoapp6-0.0.4-release.yaml, config-root/namespaces/jx-production/jx3-demoapp6/jx3-demoapp6-ingress.yaml, config-root/namespaces/jx-production/jx3-demoapp6/jx3-demoapp6-jx3-demoapp6-deploy.yaml, config-root/namespaces/jx-production/jx3-demoapp6/jx3-demoapp6-jx3-demoapp6-sa.yaml, config-root/namespaces/jx-production/jx3-demoapp6/jx3-demoapp6-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp6 to version 0.0.4 in Production environment
=> chore: promote jx3-demoapp6 to version 0.0.4 in Production environment

config-root/namespaces/jx-staging/jx3-demoapp1/jx3-demoapp1-0.0.4-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp1/jx3-demoapp1-ingress.yaml, config-root/namespaces/jx-staging/jx3-demoapp1/jx3-demoapp1-jx3-demoapp1-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp1/jx3-demoapp1-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp1 to version 0.0.4 in Staging environment
=> chore: promote jx3-demoapp1 to version 0.0.4 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp1/jx3-demoapp1-0.0.5-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp1/jx3-demoapp1-jx3-demoapp1-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp1/jx3-demoapp1-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp1 to version 0.0.5 in Staging environment
=> chore: promote jx3-demoapp1 to version 0.0.5 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp4/jx3-demoapp4-1.0.6-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp4/jx3-demoapp4-ingress.yaml, config-root/namespaces/jx-staging/jx3-demoapp4/jx3-demoapp4-jx3-demoapp4-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp4/jx3-demoapp4-jx3-demoapp4-sa.yaml, config-root/namespaces/jx-staging/jx3-demoapp4/jx3-demoapp4-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp4 to version 1.0.6 in Staging environment
=> chore: promote jx3-demoapp4 to version 1.0.6 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-0.0.32-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.32 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.32 in Staging environment

config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-1.0.10-release.yaml, config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-ingress.yaml, config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-jx3-springdemo2-deploy.yaml, config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-svc.yaml, helmfile.yaml
chore: promote jx3-springdemo2 to version 1.0.10 in Staging environment
=> chore: promote jx3-springdemo2 to version 1.0.10 in Staging environment

config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-1.0.11-release.yaml, config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-jx3-springdemo2-deploy.yaml, config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-svc.yaml, helmfile.yaml
chore: promote jx3-springdemo2 to version 1.0.11 in Staging environment
=> chore: promote jx3-springdemo2 to version 1.0.11 in Staging environment

config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-1.0.12-release.yaml, config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-jx3-springdemo2-deploy.yaml, config-root/namespaces/jx-staging/jx3-springdemo2/jx3-springdemo2-svc.yaml, helmfile.yaml
chore: promote jx3-springdemo2 to version 1.0.12 in Staging environment
=> chore: promote jx3-springdemo2 to version 1.0.12 in Staging environment

config-root/namespaces/jx-staging/jx3-demoapp2/jx3-demoapp2-0.0.1-release.yaml, config-root/namespaces/jx-staging/jx3-demoapp2/jx3-demoapp2-ingress.yaml, config-root/namespaces/jx-staging/jx3-demoapp2/jx3-demoapp2-jx3-demoapp2-deploy.yaml, config-root/namespaces/jx-staging/jx3-demoapp2/jx3-demoapp2-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp2 to version 0.0.1 in Staging environment
=> chore: promote jx3-demoapp2 to version 0.0.1 in Staging environment

config-root/namespaces/jx-production/jx3-demoapp1/jx3-demoapp1-0.0.5-release.yaml, config-root/namespaces/jx-production/jx3-demoapp1/jx3-demoapp1-ingress.yaml, config-root/namespaces/jx-production/jx3-demoapp1/jx3-demoapp1-jx3-demoapp1-deploy.yaml, config-root/namespaces/jx-production/jx3-demoapp1/jx3-demoapp1-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp1 to version 0.0.5 in Production environment
=> chore: promote jx3-demoapp1 to version 0.0.5 in Production environment

config-root/namespaces/jx-production/jx3-demoapp5/jx3-demoapp5-0.0.32-release.yaml, config-root/namespaces/jx-production/jx3-demoapp5/jx3-demoapp5-jx3-demoapp5-deploy.yaml, config-root/namespaces/jx-production/jx3-demoapp5/jx3-demoapp5-svc.yaml, helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.32 in Production environment
=> chore: promote jx3-demoapp5 to version 0.0.32 in Production environment

helmfile.yaml
chore: promote jx3-demoapp5 to version 0.0.33 in Staging environment
=> chore: promote jx3-demoapp5 to version 0.0.33 in Staging environment
